import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const bemboExtraBold = localFont({
  src: "./fonts/bembo-extra-bold.woff",
  variable: "--font-bembo-extra-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.className} ${bemboExtraBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
